language: rust
sudo: false
rust: stable
dist: trusty

matrix:
  include:
    - rust: nightly

    - env: TARGET=x86_64-unknown-linux-musl DEPLOY=1
      before_script:
        - rustup target add $TARGET
        - curl https://www.openssl.org/source/openssl-1.0.2l.tar.gz | tar xzf -
        - (cd openssl-1.0.2l &&
          CC=musl-gcc ./Configure --prefix=$HOME/openssl-musl no-dso no-ssl2 no-ssl3 linux-x86_64 -fPIC &&
          make -j$(nproc) &&
          make install)
        - export OPENSSL_DIR=$HOME/openssl-musl
      script: cargo build --release --target $TARGET --locked
      addons:
        apt:
          packages:
          - musl-tools

    - os: osx
    - os: osx
      env: MACOSX_DEPLOYMENT_TARGET=10.7 DEPLOY=1 TARGET=x86_64-apple-darwin OPENSSL_STATIC=1
      script: cargo build --release --target $TARGET --locked


script:
  - cargo test --locked

notifications:
  email:
    on_success: never

before_deploy:
  - name="cargo-local-registry-$TRAVIS_TAG-$TARGET"
  - mkdir $name
  - cp target/$TARGET/release/cargo-local-registry $name/
  - cp README.md LICENSE-MIT LICENSE-APACHE $name/
  - tar czvf $name.tar.gz $name

branches:
  only:
  - master

deploy:
  api_key:
    secure: "jwvkQVMOna+agQCnwCWUvTFniBaBxhA/x46PODfZCEPIHxQXnDVeiM3MC4aVTLF0qdUB9T8z8DwNbZYVZdC1CsmSbrITs5Xi9lT4iSSRpUXaI0sH+MuCq2z73sHJRAsHINd4fkFxrlMjH7KOWWHkaw2layxtbyOMc2d8J5tN3d38LjbMZvtoqRBKN6XitCrSGej0eEU/l3reoHOQ4gLHAxIJjF4ARxmyGfV+uin31Qyk/4OM1acHnqg18geLunwjYwV6DTXDflrLiVXMKYOizi+jciDAXPLe6M0vTPeTqc793Hy0MnijQ2bvrQzkwcd79+sXlpS4LXJ65O96DipeUJ0+zqq4VhuUpAZjvsKC8IhOFKvMynBvoaf5nV0txFG5595WkpEm0n63PB/ZpAxLrRtoT13oYajGT5s30CtF4hm+W9KDJiHAl4J0TVlI+hRm+e0roiSL/8XjzfdhYccfOp46jbOABc1PP6l+ekA+rkQk1PeANGmrSOTJxB1Ulz71t+6JMqR4ZZ4fI9yXf9Xh40VB+FtfT+H2L20L4xZG49L5jtnzDer3GwKQ3CGp4tPklkNrFNhwYQwVfeQk5BYnqHtYCtiLcixDlG9jBvl1kaBSnKxg9lqvvaoffX3IbZeoLsbm5cjR25zlYJCSJO8S8FEhAAnu3+A1D2ovFPcPP0I="
  file_glob: true
  file: cargo-local-registry-$TRAVIS_TAG-$TARGET.tar.gz
  on:
    condition: $DEPLOY = 1
    tags: true
  provider: releases
  skip_cleanup: true
