language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
script:
  - cargo test
notifications:
  email:
    on_success: never
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
os:
  - linux
  - osx
