[package]
name = "cargo-local-registry"
version = "0.1.5"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["cargo-subcommand"]
repository = "https://github.com/alexcrichton/cargo-local-registry"
homepage = "https://github.com/alexcrichton/cargo-local-registry"
documentation = "http://alexcrichton.com/cargo-local-registry"
description = """
A Cago subcommand for managing local registries.
"""

[dependencies]
cargo = "0.22"
env_logger = "0.4"
flate2 = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tar = "0.4"

[dev-dependencies]
tempdir = "0.3"
