[package]
name = "cargo-local-registry"
version = "0.1.6"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["cargo-subcommand"]
repository = "https://github.com/alexcrichton/cargo-local-registry"
homepage = "https://github.com/alexcrichton/cargo-local-registry"
documentation = "http://alexcrichton.com/cargo-local-registry"
description = """
A Cago subcommand for managing local registries.
"""

[dependencies]
cargo = "0.35"
docopt = "1.1"
env_logger = "0.6"
failure = "0.1"
flate2 = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tar = "0.4"
openssl = { version = '0.10.20', optional = true }

[dev-dependencies]
tempfile = "3.0"

[features]
vendored-openssl = ['openssl/vendored']
