[package]
name = "cargo-local-registry"
version = "0.1.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["cargo-subcommand"]
repository = "https://github.com/alexcrichton/cargo-local-registry"
homepage = "https://github.com/alexcrichton/cargo-local-registry"
documentation = "http://alexcrichton.com/cargo-local-registry"
description = """
A Cago subcommand for managing local registries.
"""

[dependencies]
cargo = "0.13"
rustc-serialize = "0.3"
tar = "0.4"
flate2 = "0.2"

[dev-dependencies]
tempdir = "0.3"
