[package]
name = "cargo-local-registry"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["cargo-subcommand"]
repository = "https://github.com/ChrisGreenaway/cargo-local-registry"
homepage = "https://github.com/ChrisGreenaway/cargo-local-registry"
description = """
A Cargo subcommand for managing local registries.
"""
edition = "2018"

[dependencies]
cargo = "0.36.0"
docopt = "1.1.0"
env_logger = "0.6.2"
failure = "0.1.0"
flate2 = "1.0.9"
serde = { version = "1.0.98", features = ['derive'] }
serde_json = "1.0.40"
tar = "0.4.26"
openssl = { version = '0.10.24', optional = true }

[dev-dependencies]
tempfile = "3.0.8"

[features]
vendored-openssl = ['openssl/vendored']
