[package]
name = "cargo-local-registry"
version = "0.1.6"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["cargo-subcommand"]
repository = "https://github.com/alexcrichton/cargo-local-registry"
homepage = "https://github.com/alexcrichton/cargo-local-registry"
documentation = "http://alexcrichton.com/cargo-local-registry"
description = """
A Cago subcommand for managing local registries.
"""
edition = "2018"

[dependencies]
cargo = "0.36.0"
docopt = "1.1.0"
env_logger = "0.6.2"
failure = "0.1.0"
flate2 = "1.0.9"
serde = { version = "1.0.94", features = ['derive'] }
serde_json = "1.0.40"
tar = "0.4.26"
openssl = { version = '0.10.23', optional = true }

[dev-dependencies]
tempfile = "3.1.0"

[features]
vendored-openssl = ['openssl/vendored']
